trigger:
- main
- pr

jobs:
  - job: Windows
    displayName: CredScan
    pool:
      vmImage: "windows-2019"
    steps:
      - task:  ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@3
        inputs:
          toolMajorVersion: 'V1'
      - task: f5679091-e6da-4974-a8dc-0eec03a8ea63@1
        inputs:
          AllTools: false
          APIScan: false
          BinSkim: false
          CodesignValidation: false
          CredScan: true
          FortifySCA: false
          FxCop: false
          ModernCop: false
          PoliCheck: false
          RoslynAnalyzers: false
          SDLNativeRules: false
          Semmle: false
          TSLint: false
          ToolLogsNotFoundAction: 'Standard'